[package]
name = "ferrumkern"
version = "0.1.0"
edition = "2021"
description = "FerrumKern — open-source x86_64 kernel, Limine boot, no_std"
license = "MIT OR Apache-2.0"

[dependencies]
limine = "0.5"
x86_64 = "0.14"
spin = "0.9"
volatile = "0.5"
uart_16550 = "0.3"
linked_list_allocator = "0.10"

[profile.dev]
panic = "abort"
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
strip = true
debug = false
